name: 使用 API 管理服務 AccountingAppBackendapi-AccountingAppBackend 建置 .NET Core 應用程式並部署到 Web 應用程式 AccountingAppBackend20250225202146
on:
  push:
    branches:
      - master
env:
  AZURE_WEBAPP_NAME: AccountingAppBackend20250225202146
  AZURE_WEBAPP_PACKAGE_PATH: AccountingAppBackend\publish
  AZURE_APIM_RESOURCE_PATH: /
  AZURE_APIM_RESOURCEGROUP: AccountingAppBackend20250225202146ResourceGroup
  AZURE_APIM_SERVICENAME: AccountingAppBackendapi
  AZURE_APIM_API_ID: AccountingAppBackend
  AZURE_APIM_APPSERVICEURL: https://accountingappbackend20250225202146.azurewebsites.net
  CONFIGURATION: Release
  DOTNET_CORE_VERSION: 8.0.x
  WORKING_DIRECTORY: AccountingAppBackend
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: |
            7.0.x
            8.0.x
      - name: Restore
        run: dotnet restore ${{ env.WORKING_DIRECTORY }}
      - name: Build
        run: dotnet build ${{ env.WORKING_DIRECTORY }} --configuration ${{ env.CONFIGURATION }} --no-restore
      - name: Test
        run: dotnet test ${{ env.WORKING_DIRECTORY }} --no-build
      - name: Publish
        run: dotnet publish ${{ env.WORKING_DIRECTORY }} --configuration ${{ env.CONFIGURATION }} --no-build --output ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
      - name: Publish Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: webapp
          path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
  deploy:
    runs-on: windows-latest
    needs: build
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: |
          8.0.x
    - name: Download artifact from build job
      uses: actions/download-artifact@v4
      with:
        name: webapp
        path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
    - name: Deploy to Azure WebApp
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
        publish-profile: ${{ secrets.AccountingAppBackend20250225202146_71C7 }}
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Install Swashbuckle CLI Locally
      run: dotnet tool install Swashbuckle.AspNetCore.Cli --version 6.2.3 --tool-path ./tools
    - name: Build and Generate Swagger JSON
      shell: cmd
      run: |
        dotnet build AccountingAppBackend.sln -c Release
        .\tools\swagger tofile --output swagger.json AccountingAppBackend\bin\Release\net8.0\AccountingAppBackend.dll v1
    - name: Import API into Azure API Management
      run: az apim api import --path "${{ env.AZURE_APIM_RESOURCE_PATH }}" --resource-group "${{ env.AZURE_APIM_RESOURCEGROUP }}" --service-name "${{ env.AZURE_APIM_SERVICENAME }}" --api-id "${{ env.AZURE_APIM_API_ID }}" --service-url "${{ env.AZURE_APIM_APPSERVICEURL }}" --specification-path "swagger.json" --specification-format OpenApi --subscription-required false
    - name: Logout
      run: az logout